name: Monorepo CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  backend:
    runs-on: ubuntu-latest

    services:
      db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - 1433:1433
        env:
          SA_PASSWORD: "Your_password123"
          ACCEPT_EULA: "Y"
        options: >-
          --health-cmd "exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v6

      # Setup .NET 10 SDK
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      # Restore, build, and test backend
      - name: Restore .NET projects
        run: dotnet restore Backend/Backend.sln

      - name: Build .NET projects
        run: dotnet build Backend/Backend.sln --no-restore --configuration Release

      - name: Run backend tests
        run: dotnet test Backend/Backend.sln --no-build --verbosity normal

      # Optional: Build and test backend Docker image
      # - name: Build backend Docker image
      #   run: docker build -t backend:ci -f Dockerfile .

  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: false
          fetch-depth: 0

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SUBMODULE_SSH_KEY }}

      - name: Update submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      # Setup Node.js
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          check-latest: true

      - name: DEBUG npm ci environment
        run: |
          pwd
          ls -la
          ls -la package-lock.json
        working-directory: Frontend/Restaurant.System.Web

      # Install Angular dependencies
      - run: npm ci
        working-directory: Frontend/Restaurant.System.Web

      # Build submodule
      - name: Build form submodule
        run: CI=true npm run build:forms
        working-directory: Frontend/Restaurant.System.Web

      # Run lint, tests, build
      - name: Lint Frontend
        run: CI=true npm run lint
        working-directory: Frontend/Restaurant.System.Web
      - name: Test Frontend
        run: CI=true npm run test -- --watch=false
        working-directory: Frontend/Restaurant.System.Web
      - name: Build Frontend
        run: CI=true npm run build:production
        working-directory: Frontend/Restaurant.System.Web
