name: Monorepo CI/CD

on:
  push:
    branches: [master, release]
  pull_request:
    branches: [master, release]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - 1433:1433
        env:
          SA_PASSWORD: "Your_password123"
          ACCEPT_EULA: "Y"
        options: >-
          --health-cmd "exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v6

      # Setup .NET 10 SDK
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      # Restore, build, and test backend
      - name: Restore .NET projects
        run: dotnet restore Backend/Backend.sln

      - name: Build .NET projects
        run: dotnet build Backend/Backend.sln --no-restore --configuration Release

      - name: Run backend tests
        run: dotnet test Backend/Backend.sln --no-build --verbosity normal

      # Optional: Build and test backend Docker image
      # - name: Build backend Docker image
      #   run: docker build -t backend:ci -f Dockerfile .

  frontend:
    runs-on: ubuntu-latest
    needs: backend

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: false

      # Setup Node.js
      - uses: actions/setup-node@v6
        with:
          node-version: '20'

      # Install Angular dependencies
      - run: npm ci
        working-directory: Frontend/Restaurant.System.Web

      # Run lint, tests, build
      - name: Lint Frontend
        run: CI=true npm run lint
        working-directory: Frontend/Restaurant.System.Web
      - name: Test Frontend
        run: CI=true npm run test -- --watch=false
        working-directory: Frontend/Restaurant.System.Web
      - name: Build Frontend
        run: CI=true npm run build
        working-directory: Frontend/Restaurant.System.Web
      
      # Deployment into Github Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with: 
          path: Frontend/Restaurant.System.Web/dist
      
  deploy-pages:
    environment: 
      name: github-pages
      url: ${{ steps.deployment.output.page_url }}
    runs-on: ubuntu-latest
    needs: frontend
    if: github.ref == 'refs/heads/release'

    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4