name: Monorepo CI/CD - Release

on:
  push:
    branches: [release]
  pull_request:
    branches: [release]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      # Setup .NET 10 SDK
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      # Build and publish Backend
      - name: Publish Backend
        # This creates a 'publish' folder containing the .dll and the wwwroot (frontend)
        run: dotnet publish Backend/Backend.sln -c Release -o ./publish

      # 4. Deploy to Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "restaurant-system" # Replace with your Azure App Name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8A01CED82F984909AC5E1DB12C7D0721 }}
          package: ./publish

  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: false
          fetch-depth: 0

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SUBMODULE_SSH_KEY }}

      - name: Update submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      # Setup Node.js
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          check-latest: true

      - name: DEBUG npm ci environment
        run: |
          pwd
          ls -la
          ls -la package-lock.json
        working-directory: Frontend/Restaurant.System.Web

      # Install Angular dependencies
      - run: npm ci
        working-directory: Frontend/Restaurant.System.Web

      - name: Build form submodule
        run: CI=true npm run build:forms
        working-directory: Frontend/Restaurant.System.Web

      - name: Build Frontend
        run: CI=true npm run build:production
        working-directory: Frontend/Restaurant.System.Web

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      # Deployment into Github Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: Frontend/Restaurant.System.Web/dist/Restaurant.System.Web/browser

  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.output.page_url }}
    runs-on: ubuntu-latest
    needs: frontend
    if: github.ref == 'refs/heads/release'

    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
